package yrc.zcc.jh.ssm.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import yrc.zcc.jh.ssm.pojo.Gm;
import yrc.zcc.jh.ssm.pojo.GmExample;

public interface GmMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gm
     *
     * @mbg.generated Thu Mar 12 18:17:24 CST 2020
     */
    long countByExample(GmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gm
     *
     * @mbg.generated Thu Mar 12 18:17:24 CST 2020
     */
    int deleteByExample(GmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gm
     *
     * @mbg.generated Thu Mar 12 18:17:24 CST 2020
     */
    int deleteByPrimaryKey(String gid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gm
     *
     * @mbg.generated Thu Mar 12 18:17:24 CST 2020
     */
    int insert(Gm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gm
     *
     * @mbg.generated Thu Mar 12 18:17:24 CST 2020
     */
    int insertSelective(Gm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gm
     *
     * @mbg.generated Thu Mar 12 18:17:24 CST 2020
     */
    List<Gm> selectByExample(GmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gm
     *
     * @mbg.generated Thu Mar 12 18:17:24 CST 2020
     */
    Gm selectByPrimaryKey(String gid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gm
     *
     * @mbg.generated Thu Mar 12 18:17:24 CST 2020
     */
    int updateByExampleSelective(@Param("record") Gm record, @Param("example") GmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gm
     *
     * @mbg.generated Thu Mar 12 18:17:24 CST 2020
     */
    int updateByExample(@Param("record") Gm record, @Param("example") GmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gm
     *
     * @mbg.generated Thu Mar 12 18:17:24 CST 2020
     */
    int updateByPrimaryKeySelective(Gm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gm
     *
     * @mbg.generated Thu Mar 12 18:17:24 CST 2020
     */
    int updateByPrimaryKey(Gm record);
}