package yrc.zcc.jh.ssm.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import yrc.zcc.jh.ssm.pojo.Kc;
import yrc.zcc.jh.ssm.pojo.KcExample;

public interface KcMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kc
     *
     * @mbg.generated Thu Mar 12 18:17:24 CST 2020
     */
    long countByExample(KcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kc
     *
     * @mbg.generated Thu Mar 12 18:17:24 CST 2020
     */
    int deleteByExample(KcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kc
     *
     * @mbg.generated Thu Mar 12 18:17:24 CST 2020
     */
    int deleteByPrimaryKey(String kcid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kc
     *
     * @mbg.generated Thu Mar 12 18:17:24 CST 2020
     */
    int insert(Kc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kc
     *
     * @mbg.generated Thu Mar 12 18:17:24 CST 2020
     */
    int insertSelective(Kc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kc
     *
     * @mbg.generated Thu Mar 12 18:17:24 CST 2020
     */
    List<Kc> selectByExample(KcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kc
     *
     * @mbg.generated Thu Mar 12 18:17:24 CST 2020
     */
    Kc selectByPrimaryKey(String kcid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kc
     *
     * @mbg.generated Thu Mar 12 18:17:24 CST 2020
     */
    int updateByExampleSelective(@Param("record") Kc record, @Param("example") KcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kc
     *
     * @mbg.generated Thu Mar 12 18:17:24 CST 2020
     */
    int updateByExample(@Param("record") Kc record, @Param("example") KcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kc
     *
     * @mbg.generated Thu Mar 12 18:17:24 CST 2020
     */
    int updateByPrimaryKeySelective(Kc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kc
     *
     * @mbg.generated Thu Mar 12 18:17:24 CST 2020
     */
    int updateByPrimaryKey(Kc record);
}