package yrc.zcc.jh.ssm.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import yrc.zcc.jh.ssm.customer.CstStudent;
import yrc.zcc.jh.ssm.pojo.Student;
import yrc.zcc.jh.ssm.pojo.StudentExample;
import yrc.zcc.jh.ssm.queryInfo.QueryInfoVal;

public interface StudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Thu Mar 12 18:17:24 CST 2020
     */
    long countByExample(StudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Thu Mar 12 18:17:24 CST 2020
     */
    int deleteByExample(StudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Thu Mar 12 18:17:24 CST 2020
     */
    int deleteByPrimaryKey(String xh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Thu Mar 12 18:17:24 CST 2020
     */
    int insert(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Thu Mar 12 18:17:24 CST 2020
     */
    int insertSelective(Student record);
    
    /**
     * 自定查询函数，使用limit关键字
     * @param queryInfoVal
     * @return
     */
    List<CstStudent> selectByQueryInfoAndLimit(QueryInfoVal queryInfoVal);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Thu Mar 12 18:17:24 CST 2020
     */
    List<Student> selectByExample(StudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Thu Mar 12 18:17:24 CST 2020
     */
    Student selectByPrimaryKey(String xh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Thu Mar 12 18:17:24 CST 2020
     */
    int updateByExampleSelective(@Param("record") Student record, @Param("example") StudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Thu Mar 12 18:17:24 CST 2020
     */
    int updateByExample(@Param("record") Student record, @Param("example") StudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Thu Mar 12 18:17:24 CST 2020
     */
    int updateByPrimaryKeySelective(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Thu Mar 12 18:17:24 CST 2020
     */
    int updateByPrimaryKey(Student record);
}