package yrc.zcc.jh.ssm.pojo;

public class Gm {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm.GID
     *
     * @mbg.generated Thu Mar 12 18:17:24 CST 2020
     */
    private String gid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm.Name
     *
     * @mbg.generated Thu Mar 12 18:17:24 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm.Email
     *
     * @mbg.generated Thu Mar 12 18:17:24 CST 2020
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm.Password
     *
     * @mbg.generated Thu Mar 12 18:17:24 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm.Username
     *
     * @mbg.generated Thu Mar 12 18:17:24 CST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm.Sex
     *
     * @mbg.generated Thu Mar 12 18:17:24 CST 2020
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm.Profe
     *
     * @mbg.generated Thu Mar 12 18:17:24 CST 2020
     */
    private String profe;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm.GID
     *
     * @return the value of gm.GID
     *
     * @mbg.generated Thu Mar 12 18:17:24 CST 2020
     */
    public String getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm.GID
     *
     * @param gid the value for gm.GID
     *
     * @mbg.generated Thu Mar 12 18:17:24 CST 2020
     */
    public void setGid(String gid) {
        this.gid = gid == null ? null : gid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm.Name
     *
     * @return the value of gm.Name
     *
     * @mbg.generated Thu Mar 12 18:17:24 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm.Name
     *
     * @param name the value for gm.Name
     *
     * @mbg.generated Thu Mar 12 18:17:24 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm.Email
     *
     * @return the value of gm.Email
     *
     * @mbg.generated Thu Mar 12 18:17:24 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm.Email
     *
     * @param email the value for gm.Email
     *
     * @mbg.generated Thu Mar 12 18:17:24 CST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm.Password
     *
     * @return the value of gm.Password
     *
     * @mbg.generated Thu Mar 12 18:17:24 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm.Password
     *
     * @param password the value for gm.Password
     *
     * @mbg.generated Thu Mar 12 18:17:24 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm.Username
     *
     * @return the value of gm.Username
     *
     * @mbg.generated Thu Mar 12 18:17:24 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm.Username
     *
     * @param username the value for gm.Username
     *
     * @mbg.generated Thu Mar 12 18:17:24 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm.Sex
     *
     * @return the value of gm.Sex
     *
     * @mbg.generated Thu Mar 12 18:17:24 CST 2020
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm.Sex
     *
     * @param sex the value for gm.Sex
     *
     * @mbg.generated Thu Mar 12 18:17:24 CST 2020
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm.Profe
     *
     * @return the value of gm.Profe
     *
     * @mbg.generated Thu Mar 12 18:17:24 CST 2020
     */
    public String getProfe() {
        return profe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm.Profe
     *
     * @param profe the value for gm.Profe
     *
     * @mbg.generated Thu Mar 12 18:17:24 CST 2020
     */
    public void setProfe(String profe) {
        this.profe = profe == null ? null : profe.trim();
    }
}