package yrc.zcc.jh.ssm.pojo;

public class Kc {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kc.KCID
     *
     * @mbg.generated Thu Mar 12 18:17:24 CST 2020
     */
    private String kcid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kc.KCMC
     *
     * @mbg.generated Thu Mar 12 18:17:24 CST 2020
     */
    private String kcmc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kc.LSM
     *
     * @mbg.generated Thu Mar 12 18:17:24 CST 2020
     */
    private String lsm;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kc.KCID
     *
     * @return the value of kc.KCID
     *
     * @mbg.generated Thu Mar 12 18:17:24 CST 2020
     */
    public String getKcid() {
        return kcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kc.KCID
     *
     * @param kcid the value for kc.KCID
     *
     * @mbg.generated Thu Mar 12 18:17:24 CST 2020
     */
    public void setKcid(String kcid) {
        this.kcid = kcid == null ? null : kcid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kc.KCMC
     *
     * @return the value of kc.KCMC
     *
     * @mbg.generated Thu Mar 12 18:17:24 CST 2020
     */
    public String getKcmc() {
        return kcmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kc.KCMC
     *
     * @param kcmc the value for kc.KCMC
     *
     * @mbg.generated Thu Mar 12 18:17:24 CST 2020
     */
    public void setKcmc(String kcmc) {
        this.kcmc = kcmc == null ? null : kcmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kc.LSM
     *
     * @return the value of kc.LSM
     *
     * @mbg.generated Thu Mar 12 18:17:24 CST 2020
     */
    public String getLsm() {
        return lsm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kc.LSM
     *
     * @param lsm the value for kc.LSM
     *
     * @mbg.generated Thu Mar 12 18:17:24 CST 2020
     */
    public void setLsm(String lsm) {
        this.lsm = lsm == null ? null : lsm.trim();
    }
}