package yrc.zcc.jh.ssm.pojo;

public class Score {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.ID
     *
     * @mbg.generated Thu Mar 12 18:17:24 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.XH
     *
     * @mbg.generated Thu Mar 12 18:17:24 CST 2020
     */
    private String xh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.KCID
     *
     * @mbg.generated Thu Mar 12 18:17:24 CST 2020
     */
    private String kcid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.Score
     *
     * @mbg.generated Thu Mar 12 18:17:24 CST 2020
     */
    private Integer score;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.ID
     *
     * @return the value of score.ID
     *
     * @mbg.generated Thu Mar 12 18:17:24 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.ID
     *
     * @param id the value for score.ID
     *
     * @mbg.generated Thu Mar 12 18:17:24 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.XH
     *
     * @return the value of score.XH
     *
     * @mbg.generated Thu Mar 12 18:17:24 CST 2020
     */
    public String getXh() {
        return xh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.XH
     *
     * @param xh the value for score.XH
     *
     * @mbg.generated Thu Mar 12 18:17:24 CST 2020
     */
    public void setXh(String xh) {
        this.xh = xh == null ? null : xh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.KCID
     *
     * @return the value of score.KCID
     *
     * @mbg.generated Thu Mar 12 18:17:24 CST 2020
     */
    public String getKcid() {
        return kcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.KCID
     *
     * @param kcid the value for score.KCID
     *
     * @mbg.generated Thu Mar 12 18:17:24 CST 2020
     */
    public void setKcid(String kcid) {
        this.kcid = kcid == null ? null : kcid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.Score
     *
     * @return the value of score.Score
     *
     * @mbg.generated Thu Mar 12 18:17:24 CST 2020
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.Score
     *
     * @param score the value for score.Score
     *
     * @mbg.generated Thu Mar 12 18:17:24 CST 2020
     */
    public void setScore(Integer score) {
        this.score = score;
    }
}